version: "3.8"
services:
  backend:
    volumes:
      - static:/static
    build: ./backend
    env_file:
      - ./backend/.env
    depends_on:
      - db
    expose:
      - 8000
    networks:
      - my-netowrk

  frontend:
    build: ./frontend
    expose:
      - 3000
    networks:
      - my-netowrk

  nginx:
    build: ./nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static:/static
    container_name: nginx
    ports:
      - 80:80
    tty: true
    restart: "on-failure"
    depends_on:
      - backend
      - frontend
    networks:
      - my-netowrk
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    ports:
      - "5434:5432"
    networks:
      - my-netowrk

volumes:
  static:

networks:
  my-netowrk:
      driver: bridge